"""
post_organize.py  —  Run from normal Python (outside UE)
Organizes PNGs from Saved/GraphPrinter/ into Saved/Screenshots/Blueprints/<module>/<asset>/
Uses asset_list.json generated by ue_open_assets.py.
"""
import os, json, shutil, glob, time

GRAPH_PRINTER_DIR = r"d:\UE\COLMM\GASPALS\Saved\GraphPrinter"
OUTPUT_ROOT       = r"d:\UE\COLMM\GASPALS\Saved\Screenshots\Blueprints"
ASSET_LIST        = r"d:\UE\COLMM\GASPALS\Tools\asset_list.json"

with open(ASSET_LIST, "r", encoding="utf-8") as f:
    assets = json.load(f)

# Build lookup: asset_name -> module
name_to_module = {a["asset_name"]: a["module"] for a in assets}

os.makedirs(OUTPUT_ROOT, exist_ok=True)

moved = 0
skipped = 0
all_pngs = glob.glob(os.path.join(GRAPH_PRINTER_DIR, "**", "*.png"), recursive=True)
print(f"Found {len(all_pngs)} PNGs in {GRAPH_PRINTER_DIR}")

for png_path in all_pngs:
    fname = os.path.basename(png_path)
    # Try to match to an asset name
    matched_asset = None
    matched_module = None
    for name, module in name_to_module.items():
        # GraphPrinter names: "Details-<Asset>.png" or "<Graph>-<Func>.png" or "<Asset>-<Func>.png"
        if name in fname:
            matched_asset  = name
            matched_module = module
            break

    if matched_asset:
        dest_dir = os.path.join(OUTPUT_ROOT, matched_module, matched_asset)
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, fname)
        if os.path.exists(dest):
            os.remove(dest)
        shutil.copy2(png_path, dest)
        print(f"  [COPY] {fname} → {matched_module}/{matched_asset}/")
        moved += 1
    else:
        # Put unmatched in _misc
        dest_dir = os.path.join(OUTPUT_ROOT, "_misc")
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, fname)
        shutil.copy2(png_path, dest)
        print(f"  [MISC] {fname}")
        skipped += 1

# Write index
index_path = os.path.join(OUTPUT_ROOT, "_index.txt")
with open(index_path, "w", encoding="utf-8") as f:
    f.write(f"GASPALS Blueprint Screenshot Index\n")
    f.write(f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write(f"Total PNGs: {len(all_pngs)}  Matched: {moved}  Misc: {skipped}\n\n")
    for asset in assets:
        asset_dir = os.path.join(OUTPUT_ROOT, asset["module"], asset["asset_name"])
        pngs_here = glob.glob(os.path.join(asset_dir, "*.png"))
        status = "OK" if pngs_here else "MISSING"
        f.write(f"{status:8} | {asset['module']:35} | {asset['asset_name']}\n")

print(f"\nDone! Moved={moved} Misc={skipped}")
print(f"Output: {OUTPUT_ROOT}")
print(f"Index:  {index_path}")
os.startfile(OUTPUT_ROOT)
